export const buttonsList = [
	{ type: 'number', value: '7' },
	{ type: 'number', value: '8' },
	{ type: 'number', value: '9' },
	{ type: 'delete', value: 'del' },
	{ type: 'number', value: '4' },
	{ type: 'number', value: '5' },
	{ type: 'number', value: '6' },
	{ type: 'operation', value: '+' },
	{ type: 'number', value: '1' },
	{ type: 'number', value: '2' },
	{ type: 'number', value: '3' },
	{ type: 'operation', value: '-' },
	{ type: 'number', value: '.' },
	{ type: 'number', value: '0' },
	{ type: 'operation', value: '/' },
	{ type: 'operation', value: 'x' },
	{ type: 'reset', value: 'reset' },
	{ type: 'result', value: '=' },
];
